package com.nmh.online_mart.mapper;

import com.nmh.online_mart.model.OrderForm;
import com.nmh.online_mart.model.OrderFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    long countByExample(OrderFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int deleteByExample(OrderFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int insert(OrderForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int insertSelective(OrderForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    List<OrderForm> selectByExample(OrderFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    OrderForm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderForm record, @Param("example") OrderFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int updateByExample(@Param("record") OrderForm record, @Param("example") OrderFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int updateByPrimaryKeySelective(OrderForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    int updateByPrimaryKey(OrderForm record);
}