package com.nmh.online_mart.mapper;

import com.nmh.online_mart.model.ProductInformation;
import com.nmh.online_mart.model.ProductInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    long countByExample(ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int deleteByExample(ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int insert(ProductInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int insertSelective(ProductInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    List<ProductInformation> selectByExampleWithBLOBs(ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    List<ProductInformation> selectByExample(ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    ProductInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductInformation record, @Param("example") ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ProductInformation record, @Param("example") ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int updateByExample(@Param("record") ProductInformation record, @Param("example") ProductInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int updateByPrimaryKeySelective(ProductInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ProductInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_information
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    int updateByPrimaryKey(ProductInformation record);
}