package com.nmh.online_mart.model;

public class OrderForm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.user_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.product_id_array
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private String productIdArray;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.gmt_create
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.total_price
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Float totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.STATUS
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.destination
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private String destination;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.id
     *
     * @return the value of order_form.id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.id
     *
     * @param id the value for order_form.id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.user_id
     *
     * @return the value of order_form.user_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.user_id
     *
     * @param userId the value for order_form.user_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.product_id_array
     *
     * @return the value of order_form.product_id_array
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public String getProductIdArray() {
        return productIdArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.product_id_array
     *
     * @param productIdArray the value for order_form.product_id_array
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setProductIdArray(String productIdArray) {
        this.productIdArray = productIdArray == null ? null : productIdArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.gmt_create
     *
     * @return the value of order_form.gmt_create
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.gmt_create
     *
     * @param gmtCreate the value for order_form.gmt_create
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.total_price
     *
     * @return the value of order_form.total_price
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Float getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.total_price
     *
     * @param totalPrice the value for order_form.total_price
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.STATUS
     *
     * @return the value of order_form.STATUS
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.STATUS
     *
     * @param status the value for order_form.STATUS
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.destination
     *
     * @return the value of order_form.destination
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.destination
     *
     * @param destination the value for order_form.destination
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }
}