package com.nmh.online_mart.model;

public class ProductInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.id
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.name
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.type
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.avatar_url
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.price
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.discount
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Float discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.sell_count
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long sellCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.view_count
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.stock
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.administrator_id
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long administratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.gmt_create
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.gmt_modified
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_information.description
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.id
     *
     * @return the value of product_information.id
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.id
     *
     * @param id the value for product_information.id
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.name
     *
     * @return the value of product_information.name
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.name
     *
     * @param name the value for product_information.name
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.type
     *
     * @return the value of product_information.type
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.type
     *
     * @param type the value for product_information.type
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.avatar_url
     *
     * @return the value of product_information.avatar_url
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.avatar_url
     *
     * @param avatarUrl the value for product_information.avatar_url
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.price
     *
     * @return the value of product_information.price
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.price
     *
     * @param price the value for product_information.price
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.discount
     *
     * @return the value of product_information.discount
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.discount
     *
     * @param discount the value for product_information.discount
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.sell_count
     *
     * @return the value of product_information.sell_count
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getSellCount() {
        return sellCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.sell_count
     *
     * @param sellCount the value for product_information.sell_count
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setSellCount(Long sellCount) {
        this.sellCount = sellCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.view_count
     *
     * @return the value of product_information.view_count
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.view_count
     *
     * @param viewCount the value for product_information.view_count
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.stock
     *
     * @return the value of product_information.stock
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.stock
     *
     * @param stock the value for product_information.stock
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.administrator_id
     *
     * @return the value of product_information.administrator_id
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.administrator_id
     *
     * @param administratorId the value for product_information.administrator_id
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setAdministratorId(Long administratorId) {
        this.administratorId = administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.gmt_create
     *
     * @return the value of product_information.gmt_create
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.gmt_create
     *
     * @param gmtCreate the value for product_information.gmt_create
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.gmt_modified
     *
     * @return the value of product_information.gmt_modified
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.gmt_modified
     *
     * @param gmtModified the value for product_information.gmt_modified
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_information.description
     *
     * @return the value of product_information.description
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_information.description
     *
     * @param description the value for product_information.description
     *
     * @mbg.generated Fri Apr 24 22:09:38 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}