package com.nmh.online_mart.model;

public class SalesRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_record.id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_record.user_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_record.product_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_record.sales_times
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long salesTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_record.sales_count
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Long salesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_record.price
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_record.id
     *
     * @return the value of sales_record.id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_record.id
     *
     * @param id the value for sales_record.id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_record.user_id
     *
     * @return the value of sales_record.user_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_record.user_id
     *
     * @param userId the value for sales_record.user_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_record.product_id
     *
     * @return the value of sales_record.product_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_record.product_id
     *
     * @param productId the value for sales_record.product_id
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_record.sales_times
     *
     * @return the value of sales_record.sales_times
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getSalesTimes() {
        return salesTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_record.sales_times
     *
     * @param salesTimes the value for sales_record.sales_times
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setSalesTimes(Long salesTimes) {
        this.salesTimes = salesTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_record.sales_count
     *
     * @return the value of sales_record.sales_count
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Long getSalesCount() {
        return salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_record.sales_count
     *
     * @param salesCount the value for sales_record.sales_count
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setSalesCount(Long salesCount) {
        this.salesCount = salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_record.price
     *
     * @return the value of sales_record.price
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_record.price
     *
     * @param price the value for sales_record.price
     *
     * @mbg.generated Mon May 11 10:56:56 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}